### ISSUE TITLE
Whats the 1 for at the beginning?

### ISSUE THREAD

**Issue by ghost** [TNorbury/Data-Compression#2]
https://github.com/TNorbury/Data-Compression/blob/dc1abe8477d9bec434e485bd1377c89e3360aa47/dataCompression.py#L216

**Comment by TNorbury** [comment]
Since this is during the flushing of the data, in the event of a kill/interrupt signal, I'm not bothering with compression since the program is exiting. As such the "1" means that there is only one of data being repeated

**Comment by TNorbury** [comment]
But since there really isn't any documentation regarding how I'm formatting each line of I figure that I should. Would you recommend putting this in a comment in the file (like at the top file) or should I create a readme file and put it in there?

**Comment by ghost** [comment]
README would be great!

Zachery Koppert

Software Engineering Manager

T/ 503.627.6938M/ 971.506.4947

tek.com<http://tek.com>

**Comment by TNorbury** [comment]
Created a readme:
https://github.com/TNorbury/Data-Compression/commit/d2fa0d352ce59ba1b68de4ccfa8692e27276fb86
